### ISSUE TITLE
iAqualink not providing info

### ISSUE THREAD

**Issue by PaulStraten** [Goose66/iaqualink-polyglotv2#1]
My Universal Devices Polisy and ISY 994 do not see anyting other than the controller node for iAqualink nodeserver.

See attached logfile.

Please help.
[iAquaLink_logs_3-9-2021_82540_PM.zip](https://github.com/Goose66/iaqualink-polyglotv2/files/6112710/iAquaLink_logs_3-9-2021_82540_PM.zip)

**Comment by Goose66** [comment]
Did you click the "Discover Devices" button in the controller node to load the device nodes for the account. See the README, specifically item # 5 in the instructions:
`5. Once the "iAquaLink NodeServer" node appears in ISY994i Adminisrative Console, click "Discover Devices" to load nodes for each of the system devices and aux relays in the pool controller(s) in your profile. THIS PROCESS MAY TAKE SEVERAL SECONDS depending on the number of systems you have and the activity on the iAqauLink service, so please be patient and wait 30 seconds or more before retrying. Also, please check the Polyglot Dashboard for messages regarding Discover Devices failure conditions.`

**Comment by PaulStraten** [comment]
Randy:

Thank you so much for quick follow-up.

I got it.

Thank you,
Paul Straten
paul@straten.com<mailto:paul@straten.com>
